### ISSUE TITLE
Block-scoped declaration not supported outside strict mode

### ISSUE THREAD

**Issue by Scream4Life** [chris1705/homebridge-secvest#3]
I installed the plugin, but when loading homebridge the secvest plugin throughs this error:

ERROR LOADING PLUGIN homebridge-secvest:
[2017-01-27 10:24:54] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:128:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:51:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Any idea? I'm running Raspbian via Noobs on a Pi2

**Comment by chris1705** [comment]
Which version of node are you using? Please update to the most recent version. You may update it by using the following tutorial: https://blog.wia.io/installing-node-js-v4-0-0-on-a-raspberry-pi

Make sure you replace the version v4.0.0 with the current one (v7.2.0) :)

Regards
Chris

**Comment by Scream4Life** [comment]
I had 4.0.0 on it. What do you mean with your last sentence? Isn't 4.0.0 not the current one?

**Comment by chris1705** [comment]
No, 4.0.0 was released 2015. Please install a newer version.

**Comment by Scream4Life** [comment]
I see what you mean. Updated now with this command 

wget https://nodejs.org/dist/v7.4.0/node-v7.4.0.tar.gz
tar -xvf node-v7.4.0.tar.gz
cd node-v7.4.0

and copied with sudo cp -R * /usr/local/

But node -v still shows the old version 4.0.0

**Comment by chris1705** [comment]
Try to uninstall the previous version of node first (sudo apt-get remove node)

**Comment by Scream4Life** [comment]
Just learned that nodejs -v gives the correct version. Or is it something different? Anyway, I still got this error when I install your plugin (even without adding it in the json)

ERROR LOADING PLUGIN homebridge-secvest:
[2017-01-30 21:51:43] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:128:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:51:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
